<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Izvjestaji\Module'                        => __DIR__ . '/Module.php',
    'Izvjestaji\Controller\IndexController' => __DIR__ . '/src/Izvjestaji/Controller/IndexController.php',
    'IzvjestajiTest\Framework\TestCase'        => __DIR__ . '/tests/Izvjestaji/Framework/TestCase.php',
    'IzvjestajiTest\SampleTest'                => __DIR__ . '/tests/Izvjestaji/SampleTest.php',
);
