<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Polao3 extends \Application\Entity\Polao3 implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'ao3_brpol', 'osnpremao', 'uk_prem_ao', 'iznosbonmal', 'bonusmalus', 'izn_doplatka', 'izn_popusta', 'zonr', 'targrupa', 'tarpodgrupa');
        }

        return array('__isInitialized__', 'ao3_brpol', 'osnpremao', 'uk_prem_ao', 'iznosbonmal', 'bonusmalus', 'izn_doplatka', 'izn_popusta', 'zonr', 'targrupa', 'tarpodgrupa');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Polao3 $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getao3_brpol()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getao3_brpol();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getao3_brpol', array());

        return parent::getao3_brpol();
    }

    /**
     * {@inheritDoc}
     */
    public function getOsnpremao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOsnpremao', array());

        return parent::getOsnpremao();
    }

    /**
     * {@inheritDoc}
     */
    public function setOsnpremao($osnpremao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOsnpremao', array($osnpremao));

        return parent::setOsnpremao($osnpremao);
    }

    /**
     * {@inheritDoc}
     */
    public function getUk_prem_ao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUk_prem_ao', array());

        return parent::getUk_prem_ao();
    }

    /**
     * {@inheritDoc}
     */
    public function setUk_prem_ao($uk_prem_ao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUk_prem_ao', array($uk_prem_ao));

        return parent::setUk_prem_ao($uk_prem_ao);
    }

    /**
     * {@inheritDoc}
     */
    public function getIznosbonmal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIznosbonmal', array());

        return parent::getIznosbonmal();
    }

    /**
     * {@inheritDoc}
     */
    public function setIznosbonmal($iznosbonmal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIznosbonmal', array($iznosbonmal));

        return parent::setIznosbonmal($iznosbonmal);
    }

    /**
     * {@inheritDoc}
     */
    public function getBonusmalus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBonusmalus', array());

        return parent::getBonusmalus();
    }

    /**
     * {@inheritDoc}
     */
    public function setBonusmalus($bonusmalus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBonusmalus', array($bonusmalus));

        return parent::setBonusmalus($bonusmalus);
    }

    /**
     * {@inheritDoc}
     */
    public function getIzn_doplatka()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIzn_doplatka', array());

        return parent::getIzn_doplatka();
    }

    /**
     * {@inheritDoc}
     */
    public function setIzn_doplatka($izn_doplatka)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIzn_doplatka', array($izn_doplatka));

        return parent::setIzn_doplatka($izn_doplatka);
    }

    /**
     * {@inheritDoc}
     */
    public function getIzn_popusta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIzn_popusta', array());

        return parent::getIzn_popusta();
    }

    /**
     * {@inheritDoc}
     */
    public function setIzn_popusta($izn_popusta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIzn_popusta', array($izn_popusta));

        return parent::setIzn_popusta($izn_popusta);
    }

    /**
     * {@inheritDoc}
     */
    public function setZonr($zonr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZonr', array($zonr));

        return parent::setZonr($zonr);
    }

    /**
     * {@inheritDoc}
     */
    public function getZonr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZonr', array());

        return parent::getZonr();
    }

    /**
     * {@inheritDoc}
     */
    public function setTargrupa($targrupa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTargrupa', array($targrupa));

        return parent::setTargrupa($targrupa);
    }

    /**
     * {@inheritDoc}
     */
    public function getTargrupa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTargrupa', array());

        return parent::getTargrupa();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarpodgrupa($tarpodgrupa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarpodgrupa', array($tarpodgrupa));

        return parent::setTarpodgrupa($tarpodgrupa);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarpodgrupa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarpodgrupa', array());

        return parent::getTarpodgrupa();
    }

}
