<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Atos osiguranje - intranet aplikacija')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))

                        ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.min.css')
                        ->appendStylesheet($this->basePath() . '/assets/css/menu.css')
                        ->appendStylesheet($this->basePath() . '/assets/css/core.css')
                        ->appendStylesheet($this->basePath() . '/assets/css/components.css')
                        ->appendStylesheet($this->basePath() . '/assets/css/icons.css')
                        ->appendStylesheet($this->basePath() . '/assets/css/pages.css')
                        ->appendStylesheet($this->basePath() . '/assets/css/responsive.css')

        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()       	
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            
            
            
            ->appendFile($this->basePath() . '/assets/js/modernizr.min.js')
        ; ?>

    </head>
    <body class="fixed-left">
    	<div id="wrapper">
    		<div class="topbar">
				<div class="topbar-left">
                    <div class="text-center">
                        <a href="<?php echo $this->url('home');?>" class="logo">
                            <img src="<?php echo $this->basePath('img/AtosLogo-small.png')?>" class="zmdi zmdi-toys icon-c-logo" style="height:65px"><!-- <span>Atos <span>intranet</span></span> -->
                            <span><img src="<?php echo $this->basePath('img/AtosLogo.png')?>" alt="logo" style="height: 52px; width:135px"></span>
                        </a>
                    </div>
                </div>
                
                <!-- Button mobilna-->
                <div class="navbar navbar-default" role="navigation">
                    <div class="container">
                        <div class="">
                            <div class="pull-left">
                                <button class="button-menu-mobile open-left waves-effect waves-light">
                                    <i class="zmdi zmdi-menu"></i>
                                </button>
                                <span class="clearfix"></span>
                            </div>
							
							<?php /*
                            <form role="search" class="navbar-left app-search pull-left hidden-xs">
			                     <input type="text" placeholder="Search..." class="form-control">
			                     <a href=""><i class="fa fa-search"></i></a>
			                </form>
			                
      */ ?>
                            <ul class="nav navbar-nav navbar-right pull-right">


                                <li class="dropdown user-box">
                                    <a href="" class="dropdown-toggle waves-effect waves-light profile " data-toggle="dropdown" aria-expanded="true">
                                        <?php if($this->layout()->korisnikImePrezime) { echo $this->layout()->korisnikImePrezime; } ?>
                                         <i class="fa fa-angle-down"></i>
                                    </a>

                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->url('user-index', array('action' => 'logout'))?>"><i class="ti-power-off m-r-5"></i> Odjava</a></li>
                                    </ul>
                                </li>
                            </ul>
                      

                        </div>
                        <!--/.nav-collapse -->
                    </div>
                </div>

    		</div>
    		<!-- Top Bar End -->
    		
    		
    		<!-- ========== Left Sidebar Start ========== -->
    		<div class="left side-menu">
                <div class="sidebar-inner slimscrollleft">
                    <!--- Divider -->
                    <div id="sidebar-menu">
                        <ul>

                        	<li class="text-muted menu-title">Opcije</li>

                            <li class="has_sub">

                                <a href="<?php echo $this->url('home');?>" class="waves-effect"><i class="zmdi zmdi-view-dashboard"></i> <span> Početna </span> </a>
                            </li>
							<?php /* 
                            <li class="has_sub">
                                <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-invert-colors"></i> <span> User Interface </span> <span class="menu-arrow"></span> </a>
                                <ul class="list-unstyled">
                                    <li><a href="ui-buttons.html">Buttons</a></li>
                                    <li><a href="ui-cards.html">Cards</a></li>
                                    <li><a href="ui-typography.html">Typography </a></li>
                                    <li><a href="ui-checkbox-radio.html">Checkboxs-Radios</a></li>
                                    <li><a href="ui-icons.html">Icons</a></li>
                                    <li><a href="ui-modals.html">Modals</a></li>
                                    <li><a href="ui-images.html">Images</a></li>
                                    <li><a href="ui-components.html">Components</a>
                                </ul>
                            </li>

                            <li class="has_sub">
                                <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-case"></i> <span> Admin UI </span> <span class="menu-arrow"></span> </a>
                                <ul class="list-unstyled">
                                    <li><a href="admin-masonry.html">Masonry</a></li>
                                    <li><a href="admin-notification.html">Notification</a></li>
                                    <li><a href="admin-range-slider.html">Range Slider</a></li>
                                    <li><a href="admin-sweetalert.html">Sweet Alert</a>
                                </ul>
                            </li>
								
                            <li class="has_sub">
                                <a href="widgets.html" class="waves-effect"><i class="zmdi zmdi-layers"></i> <span> Widgets </span> </a>
                            </li>
							*/ ?>
                            <li class="has_sub">
                                <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-collection-text"></i><span class="label label-default pull-right">6</span><span> Izvještaji </span> </a>
                                
<!--                                 <ul class="list-unstyled"> -->
                                    <!-- <li><a href="<?php // echo $this->url('izvjestaji', array('controller'=>'agencija', 'action'=>'zakljucene-polise')) ?>">Pregled polisa na dan</a></li> -->
                                    <?php echo $this->navigation('izvjestaji')->menu()->setUlClass('list-unstyled'); ?>
<!--                                 </ul> -->
                                
                            </li>
                            <?php 

					       ?>
                            
							<?php /* 
                            <li class="has_sub">
                                <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-view-list"></i> <span> Tables </span> <span class="menu-arrow"></span></a>
                                <ul class="list-unstyled">
                                	<li><a href="tables-basic.html">Basic Tables</a></li>
                                    <li><a href="tables-datatable.html">Data Table</a></li>
                                    <li><a href="tables-editable.html">Editable Table</a></li>
                                </ul>
                            </li>

                            <li class="has_sub">
                                <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-chart"></i><span> Charts </span> <span class="menu-arrow"></span></a>
                                <ul class="list-unstyled">
                                    <li><a href="chart-flot.html">Flot Chart</a></li>
                                    <li><a href="chart-morris.html">Morris Chart</a></li>
                                    <li><a href="chart-chartist.html">Chartist Charts</a></li>
                                    <li><a href="chart-other.html">Other Chart</a></li>
                                </ul>
                            </li>

                            <li class="has_sub">
                                <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-map"></i><span> Maps </span> <span class="menu-arrow"></span></a>
                                <ul class="list-unstyled">
                                    <li><a href="map-google.html">Google Maps</a></li>
                                    <li><a href="map-vector.html">Vector Maps</a></li>
                                </ul>
                            </li>

                            <li class="text-muted menu-title">More</li>

                            <li class="has_sub">
                                <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span class="label label-default pull-right">8</span><span> Pages </span></a>
                                <ul class="list-unstyled">
                                	<li><a href="page-starter.html">Starter Page</a></li>
                                    <li><a href="page-timeline.html">Timeline</a></li>
                                    <li><a href="page-login.html">Login</a></li>
                                    <li><a href="page-register.html">Register</a></li>
                                    <li><a href="page-recoverpw.html">Recover Password</a></li>
                                    <li><a href="page-lock-screen.html">Lock Screen</a></li>
                                    <li><a href="page-confirm-mail.html">Confirm Mail</a></li>
                                    <li><a href="page-404.html">Error 404</a></li>
                                </ul>
                            </li>

                            <li class="has_sub">
                                <a href="javascript:void(0);" class="waves-effect"><i class="ti-share"></i><span> Multi Level </span> <span class="menu-arrow"></span></a>
                                <ul>
                                    <li class="has_sub">
                                        <a href="javascript:void(0);" class="waves-effect"><span>Menu Level 1.1</span> <span class="menu-arrow"></span></a>
                                        <ul style="">
                                            <li><a href="javascript:void(0);"><span>Menu Level 2.1</span></a></li>
                                            <li><a href="javascript:void(0);"><span>Menu Level 2.2</span></a></li>
                                            <li><a href="javascript:void(0);"><span>Menu Level 2.3</span></a></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0);"><span>Menu Level 1.2</span></a>
                                    </li>
                                </ul>
                            </li>
                            */?>

                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>

                </div>
            </div>
			<!-- Left Sidebar End -->
			
			<!-- ============================================================== -->
			<!-- Start right Content here -->
			<!-- ============================================================== -->
				<div class="content-page">
				<!-- Start content -->
					<div class="content">		                
				     	<?php echo $this->content; ?>           
				    </div> <!-- content -->

	                <footer class="footer">
	                    2018 Atos osiguranje
	                </footer>
                </div>
			<!-- ============================================================== -->
            <!-- End Right content here -->
            <!-- ============================================================== -->
            
            
            
            <!-- Right Sidebar -->
            <?php /* 
            <div class="side-bar right-bar">
                <a href="javascript:void(0);" class="right-bar-toggle">
                    <i class="zmdi zmdi-close-circle-o"></i>
                </a>
                <h4 class="">Notifications</h4>
                <div class="notification-list nicescroll">
                    <ul class="list-group list-no-border user-list">
                        <li class="list-group-item">
                            <a href="#" class="user-list-item">
                                <div class="avatar">
                                    <img src="assets/images/users/avatar-2.jpg" alt="">
                                </div>
                                <div class="user-desc">
                                    <span class="name">Michael Zenaty</span>
                                    <span class="desc">There are new settings available</span>
                                    <span class="time">2 hours ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="list-group-item">
                            <a href="#" class="user-list-item">
                                <div class="icon">
                                    <i class="zmdi zmdi-account"></i>
                                </div>
                                <div class="user-desc">
                                    <span class="name">New Signup</span>
                                    <span class="desc">There are new settings available</span>
                                    <span class="time">5 hours ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="list-group-item">
                            <a href="#" class="user-list-item">
                                <div class="icon">
                                    <i class="zmdi zmdi-comment"></i>
                                </div>
                                <div class="user-desc">
                                    <span class="name">New Message received</span>
                                    <span class="desc">There are new settings available</span>
                                    <span class="time">1 day ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="list-group-item">
                            <a href="#" class="user-list-item">
                                <div class="avatar">
                                    <img src="assets/images/users/avatar-3.jpg" alt="">
                                </div>
                                <div class="user-desc">
                                    <span class="name">James Anderson</span>
                                    <span class="desc">There are new settings available</span>
                                    <span class="time">2 days ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="list-group-item active">
                            <a href="#" class="user-list-item">
                                <div class="icon">
                                    <i class="zmdi zmdi-settings"></i>
                                </div>
                                <div class="user-desc">
                                    <span class="name">Settings</span>
                                    <span class="desc">There are new settings available</span>
                                    <span class="time">1 day ago</span>
                                </div>
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
			*/?>
            <!-- /Right-bar -->
		</div><!-- wrapper -->
		<script>
            var resizefunc = [];
        </script>
		
				        <?php 
				        echo $this->inlineScript()
						->appendFile($this->basePath() . '/assets/js/detect.js')
						->appendFile($this->basePath() . '/assets/js/fastclick.js')
						->appendFile($this->basePath() . '/assets/js/jquery.slimscroll.js')
						->appendFile($this->basePath() . '/assets/js/jquery.blockUI.js')
						->appendFile($this->basePath() . '/assets/js/waves.js')
						->appendFile($this->basePath() . '/assets/js/wow.min.js')
						->appendFile($this->basePath() . '/assets/js/jquery.nicescroll.js')
						->appendFile($this->basePath() . '/assets/js/jquery.scrollTo.min.js')


		        		/*App js*/
		        		->appendFile($this->basePath() . '/assets/js/jquery.core.js')
		        		->appendFile($this->basePath() . '/assets/js/jquery.app.js')
		        		?>
		
		<?php echo $this->inlineSkriptContent; //trenutno ne vraca nista ?>
		
    </body>
</html>




