<?php
// foreach ($zaposleni as $zaposleni) {
//  	echo $zaposleni->getDatist()->format('d.m.Y - H:i') . ' - ';
//  	echo $zaposleni->getJmbg() . '-';
//   	echo $zaposleni->getPolao3()->getBonusmalus() . ' - ';
//  	echo $zaposleni->getPolao3()->getZonr()->getNaziv();
//  	echo $zaposleni->getPolao3()->getOsnpremao() . '<br>';
//  	echo $zaposleni->getBrojsasije();
// 		echo $zaposleni->getKorisnik();
// 		echo $zaposleni->getLozinka() . '<br>';

// }
?>


